import { slugify } from "../utils/slugify";

export interface CourseOption {
  name: string;
  duration: string;
  slug: string;
}

const rawCourses = [
  { name: "MBA", duration: "2 Years" },
  {name: "PGDM", duration: "2 Years"},
    {name: "B.Sc", duration: "3 Years"},
    {name: "B.Com", duration: "3 Years"},
    {name: "BA", duration: "3 Years"},
  { name: "B.Tech", duration: "4 Years" },
  {name: "BE", duration: "4 Years"},
  {name: "BBA", duration: "3 Years"},
    {name: "BMS", duration: "3 Years"},
    {name: "M.Sc", duration: "2 Years"},
    {name: "BCA", duration: "3 Years"},
    {name: "MA", duration: "2 Years"},
  { name: "M.Tech", duration: "2 Years" },
  {name: "ME", duration: "2 Years"},

    {name: "B.Ed", duration: "2 Years"},
    {name: "M.Com", duration: "2 Years"},
    {name: "Polytechnic", duration: "3 Years"},
    {name: "MCA", duration: "3 Years"},
  { name: "Ph.D in Science", duration: "3-5 Years" },
  {name: "M.Phil in Science", duration: "3-5 Years"},

  { name: "B.Tech Lateral", duration: "3 Years" },
  {name: "BE Lateral", duration: "3 Years"},

    {name: "B.Pharm", duration: "4 Years"},
    {name: "B.Sc-Nursing", duration: "4 Years"},
  { name: "Ph.D in Arts", duration: "3-5 Years" },
  {name: "M.Phil in Arts", duration: "3-5 Years"},
  { name: "M.Phil in Engineering", duration: "3-5 Years" },
  {name: "Ph.D in Engineering", duration: "3-5 Years"},
  { name: "Ph.D in Management", duration: "3-5 Years" },
  {name: "M.Phil in Management", duration: "3-5 Years"},
    {name: "M.Pharm", duration: "2 Years"},
    {name: "LLB", duration: "3 Years"},
  { name: "BBA LLB", duration: "5 Years" },
  {name: "BA LLB", duration: "5 Years"},
    {name: "B.Des", duration: "4 Years"},
    {name: "GNM", duration: "3 Years"},
  { name: "Ph.D in Commerce", duration: "3-5 Years" },
  {name: "M.Phil in Commerce", duration: "3-5 Years"},
    {name: "BHM", duration: "3 Years"},
    {name: "LLM", duration: "2 Years"},
    {name: "M.Ed", duration: "2 Years"},
    {name: "BMM", duration: "3 Years"},
  { name: "M.Phil in Pharmacy", duration: "3-5 Years" },
  {name: "Ph.D in Pharmacy", duration: "3-5 Years"},
    {name: "B.Pharma-Lateral", duration: "3 Years"},
    {name: "MBBS", duration: "5.5 Years"},
    {name: "M.Sc-Nursing", duration: "2 Years"},
    {name: "MD", duration: "3 Years"},
    {name: "Bachelor of Physiotherapy-BPT", duration: "4.5 Years"},
    {name: "B.Sc-Medicine", duration: "4 Years"},
    {name: "B.Sc-Agriculture", duration: "4 Years"},
    {name: "MSW", duration: "2 Years"},
    {name: "BMLT", duration: "3 Years"},
    {name: "Bachelors in Vocational Courses", duration: "3 Years"},
    {name: "MS", duration: "2 Years"},
    {name: "B.Arch", duration: "5 Years"},
  { name: "M.Phil in Law", duration: "3-5 Years" },
  {name: "Ph.D in Law", duration: "3-5 Years"},
  { name: "Ph.D in Education", duration: "3-5 Years" },
  {name: "M.Phil in Education", duration: "3-5 Years"},
    {name: "BDS", duration: "5 Years"},
  { name: "M.Phil in Medicine", duration: "3-5 Years" },
  {name: "Ph.D in Medicine", duration: "3-5 Years"},
    {name: "D.El.Ed", duration: "2 Years"},
    {name: "M.Sc-Agriculture", duration: "2 Years"},
    {name: "M.Sc-Medicine", duration: "2 Years"},
    {name: "MMC", duration: "2 Years"},
    {name: "B.P.Ed", duration: "2 Years"},
    {name: "MDS", duration: "3 Years"},
    {name: "DMLT", duration: "2 Years"},
    {name: "Bachelor of Animation", duration: "3 Years"},
    {name: "Master of Physiotherapy-MPT", duration: "2 Years"},
    {name: "Executive MBA", duration: "1 Year"},
    {name: "ANM", duration: "2 Years"},
    {name: "M.Des", duration: "2 Years"},
  { name: "M.Phil in Agriculture", duration: "3-5 Years" },
  {name: "Ph.D in Agriculture", duration: "3-5 Years"},
    {name: "D.Ed", duration: "2 Years"},
    {name: "BAMS", duration: "5.5 Years"},
    {name: "MCA-Lateral", duration: "2 Years"},
    {name: "BSW", duration: "3 Years"},
    {name: "BHM-Hospital", duration: "3 Years"},
    {name: "BFA", duration: "3 Years"},
  { name: "M.Phil in Mass Communication", duration: "3-5 Years" },
  {name: "Ph.D in Mass Communication", duration: "3-5 Years"},

    {name: "Bachelor in Aviation", duration: "3 Years"},
    {name: "Diploma in Engineering", duration: "3 Years"},
    {name: "M.Ch", duration: "3 Years"},
    {name: "M.P.Ed", duration: "2 Years"},
    {name: "Online MBA", duration: "2 Years"},
  { name: "Ph.D in Computer Applications", duration: "3-5 Years" },
  {name: "M.Phil in Computer Applications", duration: "3-5 Years"},
{name: "MHM", duration: "2 Years"},
    {name: "M.Arch", duration: "2 Years"},
    {name: "MPH", duration: "2 Years"},
    {name: "BHMS", duration: "5.5 Years"},
  { name: "M.Phil in Paramedical", duration: "3-5 Years" },
  {name: "Ph.D in Paramedical", duration: "3-5 Years"},

    {name: "MHA", duration: "2 Years"},
    {name: "MMS", duration: "2 Years"},
    {name: "M.Phil in Architecture", duration: "3-5 Years"},
  { name: "M.Phil in Design", duration: "3-5 Years" },
  {name: "Ph.D in Architecture", duration: "3-5 Years"},
  {name: "Ph.D in Design", duration: "3-5 Years"},

    {name: "Diplomate National Board-DNB", duration: "3 Years"},
  { name: "Ph.D in Dental", duration: "3-5 Years" },
  {name: "M.Phil in Dental", duration: "3-5 Years"},

    {name: "Master of Animation", duration: "2 Years"},
    {name: "MD-Ayurveda", duration: "3 Years"},
    {name: "M.Planning", duration: "2 Years"},
    {name: "Masters in Vocational Courses", duration: "2 Years"},
    {name: "BVSc", duration: "5 Years"},
    {name: "MVSc", duration: "2 Years"},
    {name: "MD-Homeopathy", duration: "3 Years"},
  { name: "M.Phil in Hotel Management", duration: "3-5 Years" },
  {name: "Ph.D in Hotel Management", duration: "3-5 Years"},

    {name: "BS", duration: "3 Years"},
    {name: "AME", duration: "3 Years"},
    {name: "Ph.D in Veterinary Science", duration: "3-5 Years"},
    {name: "B.F.Sc", duration: "4 Years"},
    {name: "BUMS", duration: "5.5 Years"},
    {name: "B.Planning", duration: "4 Years"},
    {name: "M.F.Sc", duration: "2 Years"},
    {name: "D.Litt", duration: "2+ Years"}
  ]
  
  const courseList: CourseOption[] = rawCourses.map((course) => ({
    ...course,
    slug: slugify(course.name),
  }));

export default courseList;

