import { slugify } from "../utils/slugify";

export interface EntranceExamOption {
  name: string;
  slug: string;
}

const rawEntranceExams = [
  { name: "JEE Main" },
  { name: "Jee" },
  { name: "CAT" },
  { name: "MAT" },
  { name: "NEET" },
  { name: "CMAT" },
  { name: "XAT" },
  { name: "AP ECET" },
  { name: "MHT CET" },
  { name: "CUET PG" },
  { name: "UPTAC" },
  { name: "TNEA" },
  { name: "ATMA" },
  { name: "NEET PG" },
  { name: "CUET" },
  { name: "TANCET" },
  { name: "NATA" },
  { name: "AYUSH NEET Counselling" },
  { name: "MAHCET" },
  { name: "GATE" },
  { name: "Karnataka PGCET" },
  { name: "KCET" },
  { name: "Maharashtra JEE Main" },
  { name: "AP EAPCET" },
  { name: "TS EAMCET" },
  { name: "WB CAP" },
  { name: "GPAT" },
  { name: "GMAT" },
  { name: "APICET" },
  { name: "NEET MDS" },
  { name: "MP Counselling" },
  { name: "KEAM" },
  { name: "NEET SS" },
  { name: "AP PGECET" },
  { name: "Gujarat ACPC" },
  { name: "TSICET" },
  { name: "TS PGECET" },
  { name: "KMAT" },
  { name: "GUJCET" },
  { name: "UP BEd JEE" },
  { name: "COMEDK UGET" },
  { name: "CLAT" },
  { name: "OJEE" },
  { name: "AP OAMDC" },
  { name: "NMAT" },
  { name: "MAH MCA CET" },
  { name: "AP POLYCET" },
  { name: "WBJEE" },
  { name: "HSTES" },
  { name: "JELET" },
  { name: "IPU CET" },
  { name: "TS DOST" },
  { name: "Karnataka NEET Counselling" },
  { name: "MH CET LAW" },
  { name: "NCHMCT JEE" },
  { name: "REAP" },
  { name: "AIAPGET" },
  { name: "JEE Advanced" },
  { name: "UCEED" },
  { name: "CLAT PG" },
  { name: "AIDAT" },
  { name: "CEETA PG" },
  { name: "Uttar Pradesh NEET Counselling" },
  { name: "AILET" },
  { name: "Tamil Nadu NEET Counselling" },
  { name: "KMAT KERALA" },
  { name: "Maharashtra NEET Counselling" },
  { name: "IIT JAM" },
  { name: "Chattisgarh Pre Engineering Test" },
  { name: "Bihar BEd CET" },
  { name: "Kerala NEET Counselling" },
  { name: "WBJEE ANM GNM" },
  { name: "Rajasthan NEET Counselling" },
  { name: "LSAT" },
  { name: "TS POLYCET" },
  { name: "AIMA UGAT" },
  { name: "DASA" },
  { name: "GAHET" },
  { name: "LEET" },
  { name: "WBJEE JENPAS UG" },
  { name: "Bihar UGEAC" },
  { name: "JEMAT" },
  { name: "NTA PhD Entrance Exam" },
  { name: "Gujarat NEET Counselling" },
  { name: "UP NEET PG Counselling" },
  { name: "DUET" },
  { name: "West Bengal NEET Counselling" },
  { name: "Tamil Nadu NEET PG Counselling" },
  { name: "MAH BEd CET" },
  { name: "PPMET" },
  { name: "JNU CEEB" },
  { name: "NIFT" },
  { name: "CEED" },
  { name: "JEECUP" },
  { name: "Andhra Pradesh NEET Counselling" },
  { name: "SNAP" },
  { name: "ILICAT" },
  { name: "CCMN" },
  { name: "Madhya Pradesh NEET Counselling" },
  { name: "AP EDCET" },
  { name: "INI CET" },
  { name: "Odisha CPET" },
  { name: "NID" },
  { name: "MAH M Arch CET" },
  { name: "Kerala NEET PG Counselling" },
  { name: "GRE" },
  { name: "NIMCET" },
  { name: "WB JECA" },
  { name: "UGMAC" },
  { name: "CENTAC" },
  { name: "MP Pre BEd" },
  { name: "Rajasthan JET" },
  { name: "WB NEET PG Counselling" },
  { name: "AP LAWCET" },
  { name: "COAP" },
  { name: "Punjab NEET Counselling" },
  { name: "RMCAAT" },
  { name: "KLEE" },
  { name: "Andhra Pradesh NEET PG Counselling" },
  { name: "IMU CET" },
  { name: "Haryana NEET Counselling" },
  { name: "INI SS" },
  { name: "TS EDCET" },
  { name: "NPAT" },
  { name: "MP NEET PG Counselling" },
  { name: "HPU BEd" },
  { name: "AIMA RMAT" },
  { name: "Gujarat NEET PG Counselling" },
  { name: "UKSEE" },
  { name: "CG Pre BEd" },
  { name: "AIEED" },
  { name: "Odisha NEET Counselling" },
  { name: "JCECE" },
  { name: "IBSAT" },
  { name: "SET" },
  { name: "CG PRE MCA" },
  { name: "WBUT PGET" },
  { name: "Amity JEE" },
  { name: "TANATA" },
  { name: "Himachal Pradesh NEET Counselling" },
  { name: "AIIMS BSc Nursing" },
  { name: "Assam CEE" },
  { name: "HPCET" },
  { name: "Kerala MCA" },
  { name: "MAH BHMCT CET" },
  { name: "TS PGLCET" },
  { name: "FDDI AIST" },
  { name: "MET" },
  { name: "AIIMS PG" },
  { name: "KIITEE" },
  { name: "MCAER PG CET" },
  { name: "AP PGLCET" },
  { name: "TS LAWCET" },
  { name: "SUAT" },
  { name: "BPTPIA CET" },
  { name: "GAT B" },
  { name: "ISI Admission Test" },
  { name: "JEECE" },
  { name: "AIIMS MSc" },
  { name: "NIPER JEE" },
  { name: "RTU CAM" },
  { name: "SOFT CET" },
  { name: "JSAT" },
  { name: "SRMJEEE" },
  { name: "IISER" },
  { name: "BCECE" },
  { name: "HPU MAT" },
  { name: "AEEE" },
  { name: "CG PPHT" },
  { name: "IIHM ECHAT" },
  { name: "OUCET" },
  { name: "UBTER JEEP" },
  { name: "JAC Delhi" },
  { name: "AIIMS Paramedical" },
  { name: "UPCATET" },
  { name: "MDUCEE" },
  { name: "ABVMU CNET" },
  { name: "Haryana NEET PG Counselling" },
  { name: "IIMC" },
  { name: "CUSAT CAT" },
  { name: "GLAET" },
  { name: "HCEE" },
  { name: "ITM NEST" },
  { name: "AUCET" },
  { name: "AMIETE" },
  { name: "IPMAT" },
  { name: "Tripura NEET Counselling" },
  { name: "Chhattisgarh NEET PG Counselling" },
  { name: "VITEEE" },
  { name: "IIFT" },
  { name: "BIT MCA" },
  { name: "RPVT" },
  { name: "Gujarat PGECET" },
  { name: "JAC Chandigarh" },
  { name: "Jharkhand NEET Counselling" },
  { name: "BVP CET" },
  { name: "DU JAT" },
  { name: "BUMAT" },
  { name: "KU CAT" },
  { name: "MGU CAT" },
  { name: "VITMEE" },
  { name: "RUET" },
  { name: "JUET" },
  { name: "BHU PET" },
  { name: "ULSAT" },
  { name: "CG PAT" },
  { name: "AIBE" },
  { name: "UPESMET" },
  { name: "BMAT" },
  { name: "NMIMS Entrance Test" },
  { name: "SLAT" },
  { name: "Himachal Pradesh NEET PG Counselling" },
  { name: "TISSNET" },
  { name: "BITSAT" },
  { name: "JKCET" },
  { name: "DU LLB" },
  { name: "RPET Pharmacy" },
  { name: "DPU AIBTCET" },
  { name: "IGNOU BEd Entrance Test" },
  { name: "HORTICET" },
  { name: "Rajasthan LEEP" },
  { name: "DSAT" },
  { name: "CUEE" },
  { name: "IEMJEE" },
  { name: "AUAT" },
  { name: "CEE AMPAI" },
  { name: "PU LLB" },
  { name: "BITS HD" },
  { name: "KRLMPCA CET" },
  { name: "MAH AAC CET" },
  { name: "Rajasthan PTET" },
  { name: "APJEE" },
  { name: "UPES DAT" },
  { name: "PU CET" },
  { name: "AU AIMEE Pharmacy" },
  { name: "AAEEE" },
  { name: "BHU UET" },
  { name: "SLIET SET" },
  { name: "ITSAT" },
  { name: "PESSAT" },
  { name: "GVSAT" },
  { name: "UPESEAT" },
  { name: "BEEE" },
  { name: "JUEE" },
  { name: "Andhra University Engineering Entrance Test" },
  { name: "REVA EET" },
  { name: "IUET" },
  { name: "SAAT" },
  { name: "UP Veterinary Entrance Exam" },
  { name: "OUAT" },
  { name: "Allahabad University PGAT" },
  { name: "TUEE" },
  { name: "PGIMER" },
  { name: "RULET" },
  { name: "TISS BAT" },
  { name: "FTII Entrance Exam" },
  { name: "BEET" },
  { name: "MZUEEE" },
  { name: "LFAT" },
  { name: "Allahabad University LAT" },
  { name: "Jain Entrance Test" },
  { name: "JIPMAT" },
  { name: "TS ECET" },
  { name: "UPCET" },
  { name: "NERIST Entrance Exam" },
  { name: "IIITH PGEE" },
  { name: "GCET" },
  { name: "MICAT" },
  { name: "AMUEEE" },
  { name: "DNB CET" },
  { name: "NEST" },
  { name: "BLAT" },
  { name: "Tripura JEE" },
  { name: "SRMCAT" },
  { name: "LPUNEST" },
  { name: "JIPMER" },
  { name: "KLUEEE" },
  { name: "ANUPGCET" },
  { name: "HITSEEE" },
  { name: "AISEEE" },
  { name: "VTUEEE" },
  { name: "CIEAT" },
  { name: "VSAT" },
  { name: "CMRUAT" },
  { name: "DAVUET" },
  { name: "SPSAT" },
  { name: "SRMS EET" },
  { name: "VEE" },
  { name: "PUCAT" },
  { name: "AAU VET" },
  { name: "YVUCET" },
  { name: "FRI MSc" },
  { name: "DUCET" },
  { name: "PULEET" },
  { name: "AIHMCT WAT" },
  { name: "MUCMET" },
  { name: "IIAD Entrance Exam" },
  { name: "XIC OET" },
  { name: "IICD" },
  { name: "VMOU BEd Entrance Exam" },
  { name: "GLS Institute of Design DAT" },
  { name: "APIIT NAT" },
  { name: "KLEU AIET" },
  { name: "EMAT" },
  { name: "GNIHM JET" },
  { name: "MUJEE" },
  { name: "Q Care" },
  { name: "SAEEE" },
  { name: "SMAT" },
  { name: "SRMHCAT" },
  { name: "DNB PDCET" },
  { name: "DAVV CET" },
  { name: "IIITH UGEE" },
  { name: "GMCET" },
  { name: "AME CEE" },
  { name: "JKLU DET" },
  { name: "CSAB Counselling" },
  { name: "Karnataka DCET" },
  { name: "PUBDET" },
  { name: "SMIT" },
  { name: "KIITEE Management" }
];
const entranceExamList: EntranceExamOption[] = rawEntranceExams.map((exam) => ({
  name: exam.name,
  slug: slugify(exam.name),
}));


export default entranceExamList;
